from typing import Dict
import json


class TrexMinerDataSchema:
    """Data object for logs."""

    def __init__(self, logJson: json):
        self.logSchema = {
            "accepted_count": logJson["accepted_count"],
            "active_pool__difficulty": logJson["active_pool"]["difficulty"],
            "active_pool__last_submit_ts": logJson["active_pool"]["last_submit_ts"],
            "active_pool__ping": logJson["active_pool"]["ping"],
            "active_pool__retries": logJson["active_pool"]["retries"],
            "active_pool__url": logJson["active_pool"]["url"],
            "active_pool__user": logJson["active_pool"]["user"],
            "active_pool__worker": logJson["active_pool"]["worker"],
            "algorithm": logJson["algorithm"],
            "api": logJson["api"],
            "build_date": logJson["build_date"],
            "coin": logJson["coin"],
            "description": logJson["description"],
            "driver": logJson["driver"],
            "gpu_total": logJson["gpu_total"],
            "gpus__cclock": logJson["gpus"][0]["cclock"],
            "gpus__dag_build_mode": logJson["gpus"][0]["dag_build_mode"],
            "gpus__device_id": logJson["gpus"][0]["device_id"],
            "gpus__efficiency": logJson["gpus"][0]["efficiency"],
            "gpus__fan_speed": logJson["gpus"][0]["fan_speed"],
            "gpus__gpu_id": logJson["gpus"][0]["gpu_id"],
            "gpus__gpu_user_id": logJson["gpus"][0]["gpu_user_id"],
            "gpus__hashrate": logJson["gpus"][0]["hashrate"],
            "gpus__hashrate_day": logJson["gpus"][0]["hashrate_day"],
            "gpus__hashrate_hour": logJson["gpus"][0]["hashrate_hour"],
            "gpus__hashrate_instant": logJson["gpus"][0]["hashrate_instant"],
            "gpus__hashrate_minute": logJson["gpus"][0]["hashrate_minute"],
            "gpus__intensity": logJson["gpus"][0]["intensity"],
            "gpus__lhr_tune": logJson["gpus"][0]["lhr_tune"],
            "gpus__low_load": logJson["gpus"][0]["low_load"],
            "gpus__mclock": logJson["gpus"][0]["mclock"],
            "gpus__mtweak": logJson["gpus"][0]["mtweak"],
            "gpus__name": logJson["gpus"][0]["name"],
            "gpus__paused": logJson["gpus"][0]["paused"],
            "gpus__pci_bus": logJson["gpus"][0]["pci_bus"],
            "gpus__pci_domain": logJson["gpus"][0]["pci_domain"],
            "gpus__pci_id": logJson["gpus"][0]["pci_id"],
            "gpus__potentially_unstable": logJson["gpus"][0]["potentially_unstable"],
            "gpus__power": logJson["gpus"][0]["power"],
            "gpus__power_avr": logJson["gpus"][0]["power_avr"],
            "gpus__shares__accepted_count": logJson["gpus"][0]["shares"]["accepted_count"],
            "gpus__shares__invalid_count": logJson["gpus"][0]["shares"]["invalid_count"],
            "gpus__shares__last_share_diff": logJson["gpus"][0]["shares"]["last_share_diff"],
            "gpus__shares__last_share_submit_ts": logJson["gpus"][0]["shares"]["last_share_submit_ts"],
            "gpus__shares__max_share_diff": logJson["gpus"][0]["shares"]["max_share_diff"],
            "gpus__shares__max_share_submit_ts": logJson["gpus"][0]["shares"]["max_share_submit_ts"],
            "gpus__shares__rejected_count": logJson["gpus"][0]["shares"]["rejected_count"],
            "gpus__shares__solved_count": logJson["gpus"][0]["shares"]["solved_count"],
            "gpus__temperature": logJson["gpus"][0]["temperature"],
            "gpus__uuid": logJson["gpus"][0]["uuid"],
            "gpus__vendor": logJson["gpus"][0]["vendor"],
            "hashrate": logJson["hashrate"],
            "hashrate_day": logJson["hashrate_day"],
            "hashrate_hour": logJson["hashrate_hour"],
            "hashrate_minute": logJson["hashrate_minute"],
            "invalid_count": logJson["invalid_count"],
            "name": logJson["name"],
            "os": logJson["os"],
            "paused": logJson["paused"],
            "rejected_count": logJson["rejected_count"],
            "revision": logJson["revision"],
            "sharerate": logJson["sharerate"],
            "sharerate_average": logJson["sharerate_average"],
            "solved_count": logJson["solved_count"],
            "success": logJson["success"],
            "time": logJson["time"],
            "uptime": logJson["uptime"],
            "validate_shares": logJson["validate_shares"],
            "version": logJson["version"]
        }

    def getSchema(self) -> Dict:
        """Return log object in dictionary."""
        return self.logSchema
